const ai = [
    {
        heading: 'Hume Empathetic Voice Interface',
        url: 'https://github.com/stelco/hume-voice-next-js',
        githubLink: true,
        value: 'This project features a sample implementation of Hume`s Empathic Voice Interface using Hume`s React SDK. Here, we have a simple EVI that uses the Next.js App Router.',
        value2: 'Ive integrated the Hume SDK into my portfolio and created a simple chat interface where you can interact with the EVI and have an empathatic conversation.',
        image: '/ai/hume-voice.png',
        isWorkItem: true,
        buttonLink: true,
        buttonLinkUrl: '/portfolio/ai/hume/empathatic-voice',
        isAI: true
    },
    {
        heading: 'Hume Raw Text Processor',
        url: 'https://github.com/stelco/CollinsCreativeReactNextJs/commit/e52f9e70535fd36f477f856dad13fa4d3d93ca28',
        githubLink: true,
        value: 'This project demonstrates how to use the Hume SDK with Next.js to process raw text and generate emotional responses.',
        value2: 'Ive integrated the Hume SDK into my portfolio and created a simple text processor where you can input text and see the emotional response generated by the Hume model.',
        image: '/ai/hume-raw-text.jpg',
        isWorkItem: true,
        buttonLink: true,
        buttonLinkUrl: '/portfolio/ai/hume/raw-text-processor',
        isAI: true
    },
    {
        heading: 'Next.js Gemini Chatbot',
        url: 'https://vercel.com/steven-collins-projects/cc-gemini-ai-chatbot',
        githubLink: true,
        value: 'This is an open source Chatbot template powered by the Google Gemini model built with Next.js and the AI SDK by Vercel.',
        value2: 'It currently uses the Gemini model to generate responses to user input based on planning and booking flights. It uses a PostGres database for users and chat history. I am continuing to develop this project and learning more about the various Gemini model languages.',
        image: '/ai/gemini-chatbot.jpg',
        isWorkItem: true,
        buttonLink: true,
        buttonLinkUrl: 'https://cc-gemini-ai-chatbot.vercel.app/',
        buttonLinkUrlBlank: true,
        isAI: true
    },
    {
        heading: 'PDF to Quiz Generator',
        url: 'https://github.com/stelco/pdf-to-quiz-generator',
        githubLink: true,
        value: 'This example demonstrates how to use the AI SDK with Next.js with the useObject hook to submit PDF messages to Google Gemini Generative Language API.',
        value2: 'The Gemini API allows developers to build generative AI applications using Gemini models. You can use the Gemini API for use cases like reasoning across text and images, content generation, dialogue agents, summarization and classification systems, and more.',
        image: '/ai/pdf-to-quiz-gemini.jpg',
        isWorkItem: true,
        buttonLink: true,
        buttonLinkUrl: 'https://pdf-to-quiz-generator-kappa.vercel.app/',
        buttonLinkUrlBlank: true,
        isAI: true
    },
    {
        heading: 'More to follow...',
        url: '',
        value: 'Im fascinated by AI and looking forward to adding more projects to this portfolio. Stay tuned!',
        image: '/ai/ai.jpg',
        isWorkItem: true,
        isAI: true
    }
];

export default ai;
