"use client";

import Breadcrumbs from '@/app/ui/portfolio/breadcrumbs';
import { CardIntro } from '@/app/ui/cards';
import { Button } from '@/app/ui/button';
import Image from 'next/image';

import { DisplaySentiments } from '@/app/components/ai/hume/processor/DisplaySentiments';
import React, { useState } from 'react';

export default function Page() {
  const [inputText, setInputText] = useState('Hello world im feeling motivated today and ready to take on the world!');
  const [results, setResults] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async () => {
    setLoading(true);
    try {
      const response = await fetch('/api/hume', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ text: inputText }),
      });

      if (response.ok) {
        const jobResults = await response.json();
        setResults(jobResults);
      } else {
        console.error('Failed to get job predictions');
      }
    } catch (error) {
      console.error('Failed to get job predictions:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="flex min-h-screen flex-col">

      <Breadcrumbs
        breadcrumbs={[
          { label: 'Home', href: '/portfolio/home' },
          { label: 'AI', href: '/portfolio/ai' },
          {
            label: 'Raw Text Processor',
            href: '/portfolio/ai/empathatic-voice/hume/voice',
            active: true,
          },
        ]}
      />

      <CardIntro
        CardContent={{
          title: 'Artificial Intelligence Experiments',
          value: 'Enter some text and see the emotional response generated by the Hume model.',
          buttonLink: true,
          buttonLinkUrl: '/portfolio/ai',
          value2: 'Back to AI Home Page',
        }}
      />

      <div className={"grow flex flex-col text-white dark:text-grey-100 mt-4 bg-gray-100 rounded-xl p-2 shadow-sm bg-grey-100 dark:bg-gray-600"}>
        
        <div className="flex flex-col align-bottom md:flex-row gap-4 p-4 border-b-2 rounded-b-none border-gray-100 dark:border-gray-500">

          <div className='flex flex-row grow'>
            <Image
            src="/ai/hume-raw-small.png"
            alt="Hume Voice Call"
            objectFit="contain"
            quality={100}
            height={161}
            width={100}
          />

            <textarea
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              className="mb-4 p-2 border border-gray-300 rounded"
              style={{ flex: '1' }}
            />
          </div>

          <Button
            onClick={handleSubmit}
            className="flex h-10 mt-4 items-center justify-center rounded-xl px-4 text-md font-medium text-white transition-colors bg-orange-400 hover:bg-orange-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-orange-400 dark:text-slate-800"
            style={{ alignSelf: 'center' }}
          >
            Generate Sentiments
          </Button>
        </div>

        {loading ? (
          <div className="flex justify-center items-center mt-4">
            <span className="visually-hidden text-slate-600 dark:text-slate-200">Loading your sentiments, please wait...</span>
          </div>
        ) : (
          <DisplaySentiments results={results} />
        )}
      </div>
    </main>
  );
}